#include <LiquidCrystal_1602_RUS.h>
#define buzzer 3

const byte RIGHT = 0, UP = 1, DOWN = 2, LEFT = 3, SELECT = 4, NONE = 5;


unsigned long t;

LiquidCrystal_1602_RUS lcd(8, 9, 4, 5, 6, 7);

byte getKey() {
  if (analogRead(A0) < 50) return RIGHT;
  else if (analogRead(A0) < 150) return UP;
  else if (analogRead(A0) < 350) return DOWN;
  else if (analogRead(A0) < 550) return LEFT;
  else if (analogRead(A0) < 750) return SELECT;
  else if (analogRead(A0) <= 1023) return NONE;
}

void setup() {
  pinMode(buzzer, OUTPUT);
  pinMode(10, OUTPUT);
  digitalWrite(10, HIGH);
  lcd.begin(16, 9);
  lcd.clear();
  lcd.setCursor(0, 0);
  lcd.print("Пpoпuшu кom6uнa-");
  lcd.setCursor(0, 1);
  lcd.print("цuю нa 6ymaжкe!");
  delay(4000);
  lcd.setCursor(0, 0);
  lcd.print("Дucплeй 6yдeт");
  lcd.setCursor(1, 1);
  lcd.print("cuльнo тyпuть!");
  delay(4000);
  lcd.clear();
}

void loop() {
begin:
  lcd.setCursor(0, 0);
  lcd.print(L"Кол-во правильн.");
  lcd.setCursor(0, 1);
  lcd.print(L"нажатий:     0/6");
  if (getKey() == LEFT) {
    t = millis();
    lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print(L"Кол-во правильн.");
    lcd.setCursor(0, 1);
    lcd.print(L"нажатий:     1/6");
    delay(500);
    while (true) {
      if (millis() - t > 3000) {
        t = millis();
        lcd.setCursor(1, 0);
        lcd.clear();
        lcd.print(L"Слишком");
        lcd.setCursor(4, 1);
        lcd.print(L"долго!");
        delay(1000);
        lcd.clear();
        lcd.setCursor(0, 0);
        lcd.print(L"СБРОССБРОССБРОСС");
        lcd.setCursor(0, 1);
        lcd.print(L"СБРОССБРОССБРОСС");
        delay(300);
        lcd.clear();
        lcd.setCursor(0, 0);
        lcd.print(L"БРОССБРОССБРОССБ");
        lcd.setCursor(0, 1);
        lcd.print(L"БРОССБРОССБРОССБ");
        delay(300);
        lcd.clear();
        lcd.setCursor(0, 0);
        lcd.print(L"РОССБРОССБРОССБР");
        lcd.setCursor(0, 1);
        lcd.print(L"РОССБРОССБРОССБР");
        delay(300);
        lcd.clear();
        lcd.setCursor(0, 0);
        lcd.print(L"ОССБРОССБРОССБРО");
        lcd.setCursor(0, 1);
        lcd.print(L"ОССБРОССБРОССБРО");
        delay(300);
        lcd.clear();
        lcd.setCursor(0, 0);
        lcd.print(L"ССБРОССБРОССБРОС");
        lcd.setCursor(0, 1);
        lcd.print(L"ССБРОССБРОССБРОС");
        delay(300);
        lcd.clear();
        goto begin;
      }
      if (getKey() == SELECT) {
        t = millis();
        lcd.clear();
        lcd.setCursor(0, 0);
        lcd.print(L"Кол-во правильн.");
        lcd.setCursor(0, 1);
        lcd.print(L"нажатий:     2/6");
        delay(500);
        while (true) {
          if (millis() - t > 3000) {
            t = millis();
            lcd.setCursor(1, 0);
            lcd.clear();
            lcd.print(L"Слишком");
            lcd.setCursor(4, 1);
            lcd.print(L"долго!");
            delay(1000);
            lcd.clear();
            lcd.setCursor(0, 0);
            lcd.print(L"СБРОССБРОССБРОСС");
            lcd.setCursor(0, 1);
            lcd.print(L"СБРОССБРОССБРОСС");
            delay(300);
            lcd.clear();
            lcd.setCursor(0, 0);
            lcd.print(L"БРОССБРОССБРОССБ");
            lcd.setCursor(0, 1);
            lcd.print(L"БРОССБРОССБРОССБ");
            delay(300);
            lcd.clear();
            lcd.setCursor(0, 0);
            lcd.print(L"РОССБРОССБРОССБР");
            lcd.setCursor(0, 1);
            lcd.print(L"РОССБРОССБРОССБР");
            delay(300);
            lcd.clear();
            lcd.setCursor(0, 0);
            lcd.print(L"ОССБРОССБРОССБРО");
            lcd.setCursor(0, 1);
            lcd.print(L"ОССБРОССБРОССБРО");
            delay(300);
            lcd.clear();
            lcd.setCursor(0, 0);
            lcd.print(L"ССБРОССБРОССБРОС");
            lcd.setCursor(0, 1);
            lcd.print(L"ССБРОССБРОССБРОС");
            delay(300);
            lcd.clear();
            goto begin;
          }
          if (getKey() == UP) {
            t = millis();
            lcd.clear();
            lcd.setCursor(0, 0);
            lcd.print(L"Кол-во правильн.");
            lcd.setCursor(0, 1);
            lcd.print(L"нажатий:     3/6");
            delay(500);
            while (true) {
              if (millis() - t > 3000) {
                t = millis();
                lcd.setCursor(1, 0);
                lcd.clear();
                lcd.print(L"Слишком");
                lcd.setCursor(4, 1);
                lcd.print(L"долго!");
                delay(1000);
                lcd.clear();
                lcd.setCursor(0, 0);
                lcd.print(L"СБРОССБРОССБРОСС");
                lcd.setCursor(0, 1);
                lcd.print(L"СБРОССБРОССБРОСС");
                delay(300);
                lcd.clear();
                lcd.setCursor(0, 0);
                lcd.print(L"БРОССБРОССБРОССБ");
                lcd.setCursor(0, 1);
                lcd.print(L"БРОССБРОССБРОССБ");
                delay(300);
                lcd.clear();
                lcd.setCursor(0, 0);
                lcd.print(L"РОССБРОССБРОССБР");
                lcd.setCursor(0, 1);
                lcd.print(L"РОССБРОССБРОССБР");
                delay(300);
                lcd.clear();
                lcd.setCursor(0, 0);
                lcd.print(L"ОССБРОССБРОССБРО");
                lcd.setCursor(0, 1);
                lcd.print(L"ОССБРОССБРОССБРО");
                delay(300);
                lcd.clear();
                lcd.setCursor(0, 0);
                lcd.print(L"ССБРОССБРОССБРОС");
                lcd.setCursor(0, 1);
                lcd.print(L"ССБРОССБРОССБРОС");
                delay(300);
                lcd.clear();
                goto begin;
              }
              if (getKey() == DOWN) {
                t = millis();
                lcd.clear();
                lcd.setCursor(0, 0);
                lcd.print(L"Кол-во правильн.");
                lcd.setCursor(0, 1);
                lcd.print(L"нажатий:     4/6");
                delay(500);
                while (true) {
                  if (millis() - t > 3000) {
                    t = millis();
                    lcd.setCursor(1, 0);
                    lcd.clear();
                    lcd.print(L"Слишком");
                    lcd.setCursor(4, 1);
                    lcd.print(L"долго!");
                    delay(1000);
                    lcd.clear();
                    lcd.setCursor(0, 0);
                    lcd.print(L"СБРОССБРОССБРОСС");
                    lcd.setCursor(0, 1);
                    lcd.print(L"СБРОССБРОССБРОСС");
                    delay(300);
                    lcd.clear();
                    lcd.setCursor(0, 0);
                    lcd.print(L"БРОССБРОССБРОССБ");
                    lcd.setCursor(0, 1);
                    lcd.print(L"БРОССБРОССБРОССБ");
                    delay(300);
                    lcd.clear();
                    lcd.setCursor(0, 0);
                    lcd.print(L"РОССБРОССБРОССБР");
                    lcd.setCursor(0, 1);
                    lcd.print(L"РОССБРОССБРОССБР");
                    delay(300);
                    lcd.clear();
                    lcd.setCursor(0, 0);
                    lcd.print(L"ОССБРОССБРОССБРО");
                    lcd.setCursor(0, 1);
                    lcd.print(L"ОССБРОССБРОССБРО");
                    delay(300);
                    lcd.clear();
                    lcd.setCursor(0, 0);
                    lcd.print(L"ССБРОССБРОССБРОС");
                    lcd.setCursor(0, 1);
                    lcd.print(L"ССБРОССБРОССБРОС");
                    delay(300);
                    lcd.clear();
                    goto begin;
                  }
                  if (getKey() == SELECT) {
                    t = millis();
                    lcd.clear();
                    lcd.setCursor(0, 0);
                    lcd.print(L"Кол-во правильн.");
                    lcd.setCursor(0, 1);
                    lcd.print(L"нажатий:     5/6");
                    delay(500);
                    while (true) {
                      if (millis() - t > 3000) {
                        t = millis();
                        lcd.setCursor(1, 0);
                        lcd.clear();
                        lcd.print(L"Слишком");
                        lcd.setCursor(4, 1);
                        lcd.print(L"долго!");
                        delay(1000);
                        lcd.clear();
                        lcd.setCursor(0, 0);
                        lcd.print(L"СБРОССБРОССБРОСС");
                        lcd.setCursor(0, 1);
                        lcd.print(L"СБРОССБРОССБРОСС");
                        delay(300);
                        lcd.clear();
                        lcd.setCursor(0, 0);
                        lcd.print(L"БРОССБРОССБРОССБ");
                        lcd.setCursor(0, 1);
                        lcd.print(L"БРОССБРОССБРОССБ");
                        delay(300);
                        lcd.clear();
                        lcd.setCursor(0, 0);
                        lcd.print(L"РОССБРОССБРОССБР");
                        lcd.setCursor(0, 1);
                        lcd.print(L"РОССБРОССБРОССБР");
                        delay(300);
                        lcd.clear();
                        lcd.setCursor(0, 0);
                        lcd.print(L"ОССБРОССБРОССБРО");
                        lcd.setCursor(0, 1);
                        lcd.print(L"ОССБРОССБРОССБРО");
                        delay(300);
                        lcd.clear();
                        lcd.setCursor(0, 0);
                        lcd.print(L"ССБРОССБРОССБРОС");
                        lcd.setCursor(0, 1);
                        lcd.print(L"ССБРОССБРОССБРОС");
                        delay(300);
                        lcd.clear();
                        goto begin;
                      }
                      if (getKey() == RIGHT) {
                        lcd.clear();
                        lcd.setCursor(0, 0);
                        lcd.print(L"Кол-во правильн.");
                        lcd.setCursor(0, 1);
                        lcd.print(L"нажатий:     6/6");
                        delay(1000);
                        lcd.clear();
                        tone(buzzer, 261.63, 300);
                        delay(350);
                        tone(buzzer, 261.63, 100);
                        delay(150);
                        tone(buzzer, 293.66, 400);
                        delay(450);
                        tone(buzzer, 261.63, 400);
                        delay(450);
                        tone(buzzer, 349.23, 400);
                        delay(450);
                        tone(buzzer, 329.63, 800);
                        delay(850);
                        tone(buzzer, 261.63, 300);
                        delay(350);
                        tone(buzzer, 261.63, 100);
                        delay(150);
                        lcd.setCursor(0, 0);
                        lcd.print(L"С днём рождения!");
                        tone(buzzer, 293.66, 400);
                        delay(450);
                        tone(buzzer, 261.63, 400);
                        delay(450);
                        tone(buzzer, 392.00, 400);
                        delay(450);
                        lcd.setCursor(0, 1);
                        lcd.print(L"TыЛyчшaяMamoчкa!");
                        tone(buzzer, 349.23, 800);
                        delay(850);
                        tone(buzzer, 261.63, 300);
                        delay(350);
                        tone(buzzer, 261.63, 100);
                        delay(150);
                        tone(buzzer, 523.25, 400);
                        delay(450);
                        tone(buzzer, 440.00, 400);
                        lcd.clear();
                        delay(450);
                        tone(buzzer, 349.23, 300);
                        delay(350);
                        tone(buzzer, 349.23, 100);
                        delay(150);
                        tone(buzzer, 329.63, 400);
                        delay(450);
                        tone(buzzer, 293.66, 400);
                        delay(450);
                        lcd.setCursor(1, 0);
                        lcd.print(L"Пoд 6oгaтыp-");
                        lcd.setCursor(3, 1);
                        lcd.print(L"cкum шлemоm");
                        tone(buzzer, 466.16, 300);
                        delay(350);
                        tone(buzzer, 466.16, 100);
                        delay(150);
                        tone(buzzer, 440.00, 400);
                        delay(450);
                        tone(buzzer, 349.23, 400);
                        delay(450);
                        tone(buzzer, 392.00, 400);
                        delay(450);
                        tone(buzzer, 349.23, 400);
                        delay(2000);
                        lcd.clear();
                        delay(1000);
                        lcd.setCursor(3, 1);
                        lcd.print(L"=)");
                        delay(1000);
                        lcd.setCursor(3, 1);
                        lcd.print(L"=O");
                        lcd.setCursor(6, 0);
                        lcd.print(L"Mяy!");
                        delay(2000);
                        lcd.setCursor(3, 1);
                        lcd.print(L"=)");
                        lcd.setCursor(6, 0);
                        lcd.print(L"    ");
                        delay(2000);
                        lcd.clear();
                        digitalWrite(10, LOW);
                        while (true) {}
                      } else if (getKey() == LEFT || getKey() == UP || getKey() == DOWN || getKey() == SELECT) {
                        t = millis();
                        lcd.setCursor(5, 0);
                        lcd.clear();
                        lcd.print(L"Не та");
                        lcd.setCursor(9, 1);
                        lcd.print(L"кнопка!");
                        delay(1000);
                        lcd.clear();
                        lcd.setCursor(0, 0);
                        lcd.print(L"СБРОССБРОССБРОСС");
                        lcd.setCursor(0, 1);
                        lcd.print(L"СБРОССБРОССБРОСС");
                        delay(300);
                        lcd.clear();
                        lcd.setCursor(0, 0);
                        lcd.print(L"БРОССБРОССБРОССБ");
                        lcd.setCursor(0, 1);
                        lcd.print(L"БРОССБРОССБРОССБ");
                        delay(300);
                        lcd.clear();
                        lcd.setCursor(0, 0);
                        lcd.print(L"РОССБРОССБРОССБР");
                        lcd.setCursor(0, 1);
                        lcd.print(L"РОССБРОССБРОССБР");
                        delay(300);
                        lcd.clear();
                        lcd.setCursor(0, 0);
                        lcd.print(L"ОССБРОССБРОССБРО");
                        lcd.setCursor(0, 1);
                        lcd.print(L"ОССБРОССБРОССБРО");
                        delay(300);
                        lcd.clear();
                        lcd.setCursor(0, 0);
                        lcd.print(L"ССБРОССБРОССБРОС");
                        lcd.setCursor(0, 1);
                        lcd.print(L"ССБРОССБРОССБРОС");
                        delay(300);
                        lcd.clear();
                        goto begin;
                      }
                    }
                  } else if (getKey() == LEFT || getKey() == UP || getKey() == DOWN || getKey() == RIGHT) {
                    t = millis();
                    lcd.setCursor(5, 0);
                    lcd.clear();
                    lcd.print(L"Не та");
                    lcd.setCursor(9, 1);
                    lcd.print(L"кнопка!");
                    delay(1000);
                    lcd.clear();
                    lcd.setCursor(0, 0);
                    lcd.print(L"СБРОССБРОССБРОСС");
                    lcd.setCursor(0, 1);
                    lcd.print(L"СБРОССБРОССБРОСС");
                    delay(300);
                    lcd.clear();
                    lcd.setCursor(0, 0);
                    lcd.print(L"БРОССБРОССБРОССБ");
                    lcd.setCursor(0, 1);
                    lcd.print(L"БРОССБРОССБРОССБ");
                    delay(300);
                    lcd.clear();
                    lcd.setCursor(0, 0);
                    lcd.print(L"РОССБРОССБРОССБР");
                    lcd.setCursor(0, 1);
                    lcd.print(L"РОССБРОССБРОССБР");
                    delay(300);
                    lcd.clear();
                    lcd.setCursor(0, 0);
                    lcd.print(L"ОССБРОССБРОССБРО");
                    lcd.setCursor(0, 1);
                    lcd.print(L"ОССБРОССБРОССБРО");
                    delay(300);
                    lcd.clear();
                    lcd.setCursor(0, 0);
                    lcd.print(L"ССБРОССБРОССБРОС");
                    lcd.setCursor(0, 1);
                    lcd.print(L"ССБРОССБРОССБРОС");
                    delay(300);
                    lcd.clear();
                    goto begin;
                  }
                }
              } else if (getKey() == LEFT || getKey() == UP || getKey() == RIGHT || getKey() == SELECT) {
                t = millis();
                lcd.setCursor(5, 0);
                lcd.clear();
                lcd.print(L"Не та");
                lcd.setCursor(9, 1);
                lcd.print(L"кнопка!");
                delay(1000);
                lcd.clear();
                lcd.setCursor(0, 0);
                lcd.print(L"СБРОССБРОССБРОСС");
                lcd.setCursor(0, 1);
                lcd.print(L"СБРОССБРОССБРОСС");
                delay(300);
                lcd.clear();
                lcd.setCursor(0, 0);
                lcd.print(L"БРОССБРОССБРОССБ");
                lcd.setCursor(0, 1);
                lcd.print(L"БРОССБРОССБРОССБ");
                delay(300);
                lcd.clear();
                lcd.setCursor(0, 0);
                lcd.print(L"РОССБРОССБРОССБР");
                lcd.setCursor(0, 1);
                lcd.print(L"РОССБРОССБРОССБР");
                delay(300);
                lcd.clear();
                lcd.setCursor(0, 0);
                lcd.print(L"ОССБРОССБРОССБРО");
                lcd.setCursor(0, 1);
                lcd.print(L"ОССБРОССБРОССБРО");
                delay(300);
                lcd.clear();
                lcd.setCursor(0, 0);
                lcd.print(L"ССБРОССБРОССБРОС");
                lcd.setCursor(0, 1);
                lcd.print(L"ССБРОССБРОССБРОС");
                delay(300);
                lcd.clear();
                goto begin;
              }
            }
          } else if (getKey() == LEFT || getKey() == RIGHT || getKey() == DOWN || getKey() == SELECT) {
            t = millis();
            lcd.setCursor(5, 0);
            lcd.clear();
            lcd.print(L"Не та");
            lcd.setCursor(9, 1);
            lcd.print(L"кнопка!");
            delay(1000);
            lcd.clear();
            lcd.setCursor(0, 0);
            lcd.print(L"СБРОССБРОССБРОСС");
            lcd.setCursor(0, 1);
            lcd.print(L"СБРОССБРОССБРОСС");
            delay(300);
            lcd.clear();
            lcd.setCursor(0, 0);
            lcd.print(L"БРОССБРОССБРОССБ");
            lcd.setCursor(0, 1);
            lcd.print(L"БРОССБРОССБРОССБ");
            delay(300);
            lcd.clear();
            lcd.setCursor(0, 0);
            lcd.print(L"РОССБРОССБРОССБР");
            lcd.setCursor(0, 1);
            lcd.print(L"РОССБРОССБРОССБР");
            delay(300);
            lcd.clear();
            lcd.setCursor(0, 0);
            lcd.print(L"ОССБРОССБРОССБРО");
            lcd.setCursor(0, 1);
            lcd.print(L"ОССБРОССБРОССБРО");
            delay(300);
            lcd.clear();
            lcd.setCursor(0, 0);
            lcd.print(L"ССБРОССБРОССБРОС");
            lcd.setCursor(0, 1);
            lcd.print(L"ССБРОССБРОССБРОС");
            delay(300);
            lcd.clear();
            goto begin;
          }
        }
      } else if (getKey() == LEFT || getKey() == UP || getKey() == DOWN || getKey() == RIGHT) {
        t = millis();
        lcd.setCursor(5, 0);
        lcd.clear();
        lcd.print(L"Не та");
        lcd.setCursor(9, 1);
        lcd.print(L"кнопка!");
        delay(1000);
        lcd.clear();
        lcd.setCursor(0, 0);
        lcd.print(L"СБРОССБРОССБРОСС");
        lcd.setCursor(0, 1);
        lcd.print(L"СБРОССБРОССБРОСС");
        delay(300);
        lcd.clear();
        lcd.setCursor(0, 0);
        lcd.print(L"БРОССБРОССБРОССБ");
        lcd.setCursor(0, 1);
        lcd.print(L"БРОССБРОССБРОССБ");
        delay(300);
        lcd.clear();
        lcd.setCursor(0, 0);
        lcd.print(L"РОССБРОССБРОССБР");
        lcd.setCursor(0, 1);
        lcd.print(L"РОССБРОССБРОССБР");
        delay(300);
        lcd.clear();
        lcd.setCursor(0, 0);
        lcd.print(L"ОССБРОССБРОССБРО");
        lcd.setCursor(0, 1);
        lcd.print(L"ОССБРОССБРОССБРО");
        delay(300);
        lcd.clear();
        lcd.setCursor(0, 0);
        lcd.print(L"ССБРОССБРОССБРОС");
        lcd.setCursor(0, 1);
        lcd.print(L"ССБРОССБРОССБРОС");
        delay(300);
        lcd.clear();
        goto begin;
      }
    }
  } else if (getKey() == SELECT || getKey() == UP || getKey() == DOWN || getKey() == RIGHT) {
    t = millis();
    lcd.setCursor(5, 0);
    lcd.clear();
    lcd.print(L"Не та");
    lcd.setCursor(9, 1);
    lcd.print(L"кнопка!");
    delay(1000);
    lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print(L"СБРОССБРОССБРОСС");
    lcd.setCursor(0, 1);
    lcd.print(L"СБРОССБРОССБРОСС");
    delay(300);
    lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print(L"БРОССБРОССБРОССБ");
    lcd.setCursor(0, 1);
    lcd.print(L"БРОССБРОССБРОССБ");
    delay(300);
    lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print(L"РОССБРОССБРОССБР");
    lcd.setCursor(0, 1);
    lcd.print(L"РОССБРОССБРОССБР");
    delay(300);
    lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print(L"ОССБРОССБРОССБРО");
    lcd.setCursor(0, 1);
    lcd.print(L"ОССБРОССБРОССБРО");
    delay(300);
    lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print(L"ССБРОССБРОССБРОС");
    lcd.setCursor(0, 1);
    lcd.print(L"ССБРОССБРОССБРОС");
    delay(300);
    lcd.clear();
    goto begin;
  }
}
